### PR TITLE
#7 Find an existing local repository

### PR DESCRIPTION
**Pull request by Mojachieee**
Addresses #7

### CODE REVIEW

**Comment by jdalrymple** [comment]
This functionality is already present i believe. Simply use Hg.getRepo({path: 'some/path/to/repo'}) ill Add to the docs to clarify!

**Comment by Mojachieee** [comment]
`Hg.getRepo` will always be caught on this line:
``if (Fs.pathExistsSync(this.path)) throw new Error(`Repository already exists at this path: ${this.path}`);``

Would you like me to amend getRepo to make it work?

**Comment by jdalrymple** [comment]
Truth, I'll look into it!

**Comment by jdalrymple** [comment]
Hmm I'm not sure if adding an extra parameter to the constructor is the best way of doing it.  That i can think of we could:

1. Add the parameter to the constructor that acts as a flag to check for the directory or not
2. Embed the logic in the functions that call the constructor like Hg.create, Hg.clone and not within functions like getRepo
3. ...Other ideas here

The real question is whether the constructor should be creating the folder structure, or just be a reference to a repository?

**Comment by jdalrymple** [comment]
I pushed up an example of having the check in the functions themselves, still rough work, but check it out to see if it makes sense. The branch is called finding-an-existing-local-repository

**Comment by Mojachieee** [comment]
> The real question is whether the constructor should be creating the folder structure, or just be a reference to a repository?

I think it should just be a reference to the repository. 

The branch looks good. Perhaps `getRepo` should check if the local repository exists (I guess just check for a .hg folder?).

**Comment by jdalrymple** [comment]
Making those changes now! Just ensuring all the tests work properly :)

**Comment by jdalrymple** [comment]
K, its been pushed up, if you have a chance, give it a look to make sure i didnt miss anything important!

**Comment by Mojachieee** [comment]
This looks good. 

My initial test works fine.

**Pull request merged**
